# Generated by Django 4.2.4 on 2023-09-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='products',
            name='SupplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.suppliers'),
        ),
    ]
